name: openmm
channels:
  - conda-forge
dependencies:
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - contourpy=1.3.3=py312ha0dd364_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dftd4=3.7.0=hb3fdf34_4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312h5748b74_0
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.2.4=py312h6b01ec3_1
  - icu=75.1=hfee45f7_0
  - khronos-opencl-icd-loader=2024.10.24=h5505292_1
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=37_h51639a9_openblas
  - libboost=1.86.0=hf493ff8_4
  - libboost-python=1.86.0=py312habbcb05_4
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcxx=21.1.3=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=h1bb475b_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=37_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libpng=1.6.50=h280e0eb_1
  - libpq=18.0=h31f7a3a_0
  - librdkit=2025.09.1=hab8bf10_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.1=h7dc4979_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.3=h4a912ad_0
  - matplotlib-base=3.10.6=py312h605b88b_1
  - mctc-lib=0.4.1=hdbc710d_0
  - multicharge=0.3.0=hb3fdf34_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - ocl_icd_wrapper_apple=1.0.0=h27ca646_0
  - opencl-headers=2025.06.13=h286801f_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openmm=8.2.0=py312h505867f_3_khronos
  - openmm-xtb=0.3=py312hd8f9ff3_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312h5978115_1
  - pcre2=10.46=h7125dd6_0
  - pdbfixer=1.12=pyhd8ed1ab_0
  - pillow=11.3.0=py312h2525f64_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycairo=1.28.0=py312h0012f17_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.12.12=hec0b533_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - rdkit=2025.09.1=py312hc147c13_0
  - readline=8.2=h1d1bf99_2
  - reportlab=4.4.4=py312h4409184_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - scipy=1.16.2=py312ha6bbf71_0
  - setuptools=80.9.0=pyhff2d567_0
  - simple-dftd3=1.2.1=hb42fc24_1
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.44=py312h4409184_0
  - tblite=0.4.0=hb3fdf34_2
  - tk=8.6.13=h892fb3f_2
  - toml-f=0.4.2=h64a7517_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h163523d_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xtb=6.7.1=h1aae681_4
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - anyio==4.12.0
      - bio==1.8.1
      - biopython==1.86
      - biothings-client==0.4.1
      - certifi==2025.11.12
      - et-xmlfile==2.0.0
      - filelock==3.20.1
      - gprofiler-official==1.0.0
      - griddataformats==1.0.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - joblib==1.5.3
      - mda-xdrlib==0.2.0
      - mdanalysis==2.10.0
      - mdtraj==1.11.0
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.1.2
      - mygene==3.2.2
      - numpy==1.26.4
      - openpyxl==3.1.5
      - platformdirs==4.5.1
      - pooch==1.8.2
      - requests==2.32.5
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - urllib3==2.6.2
prefix: /Users/apple/miniforge3/envs/openmm
